Update SEC page content
LLK/scratch-www pull request #4843
Opened 2021-01-12 21:00 UTC by paulkaplan

Resolves https://github.com/LLK/scratch-www/issues/4842

2021-01-12 22:16 UTC, seotts commented
It's looking good overall, but there are a few cases where it doesn't quite line up with the proposed changes.

2021-01-13 14:18 UTC, seotts requested changes

2021-01-13 14:29 UTC, paulkaplan commented on src/views/sec/sec.jsx
>                  </FlexRow>
Fixed!

2021-01-13 14:30 UTC, paulkaplan commented on src/views/sec/l10n.json
>    "sec.applyDeadline": "The deadline for applying to the Scratch Education Collaborative is January 10th, 2021",
Fixed

2021-01-13 14:30 UTC, paulkaplan commented on src/views/sec/sec.jsx
>                      <li><FormattedMessage id="sec.eligibilityPoint1" /></li>
Fixed

2021-01-13 14:30 UTC, paulkaplan commented on src/views/sec/l10n.json
> -  "sec.projectsIntro": "The Scratch Foundation, with help from Google.org, is launching the Scratch Education Collaborative (SEC), to bring together organizations committed to supporting creative cod
I think KO's comment is that it will not be a link? Also fixed the bold part

2021-01-13 14:30 UTC, paulkaplan commented on src/views/sec/l10n.json
> +  "sec.applyBanner": "Applications are open now through March 1st 2021",
Fixed good catch

2021-01-13 14:35 UTC, seotts commented on src/views/sec/l10n.json
> -  "sec.projectsIntro": "The Scratch Foundation, with help from Google.org, is launching the Scratch Education Collaborative (SEC), to bring together organizations committed to supporting creative cod
oops, misread it!

2021-01-13 14:50 UTC, seotts approved these changes
The changes look good! I notice that the google doc uses bullet points in the FAQ section, whereas this uses paragraphs. Assuming that is an intentional choice, lgtm.

2021-01-13 15:18 UTC, merged