Reset studio comments when admin logs in
LLK/scratch-www pull request #5280
Opened 2021-04-22 15:43 UTC by paulkaplan

### Resolves:

Resolves an issue we found in testing where an admin user might navigate directly to /studios-playground/123/comments and would see the comments as if they weren't an admin. The reason is that comments do not wait to load for the user session to return, because for almost all users it doesn't matter. But admins see reported comments, so the comment list either has to wait for the user session to return (slowing down the experience for all users) or reset the comment list when the session returns as an admin (possibly causing a layout shift only for admins as their logged out comment list gets replaced by the admin one). I chose the second option, since it will provide the fastest experience for far more people.

### Changes:

_Describe what this Pull Request does. Be sure to include a brief description of the issue the Pull Requests solves too._

Instead of only loading the initial comment list on first render, I added `comments.length === 0` to the effect hook dependency list, so it will re-load comments any time that number changes to 0 (or initially). 

Then I added another effect hook that uses `useRef` to track the previous value of `isAdmin`, and compares it against the new value (this is like `prevProps.X !== props.X` in componentDidUpdate). If the user "becomes" an admin, the comments are reset, which then gets the comments reloaded. 

### Test Coverage:

_Please show how you have added tests to cover your changes or describe how you have tested the changes (include a screenshot if possible)._

Added a unit test for the `studio-comment` component (and exported the unconnected version for simpler testing). It tests the situations when the initial comment load is called, and when the admin reset is called.

2021-04-22 15:44 UTC, paulkaplan commented on src/views/studio/studio-comments.jsx
> +    const adminRef = useRef(isAdmin);
refs are often used to hold on to DOM nodes, but they actually can contain any mutable value (they return an object with a `.current` property, you can assign whatever you want to it). The first argument to `useRef` is the initial current value, if the ref hasn't already been created. https://reactjs.org/docs/hooks-reference.html#useref

2021-04-28 15:18 UTC, kchadha commented on src/views/studio/studio-comments.jsx
> +    }, [isAdmin]);
To confirm I'm reading this right...
Does this mean that handleResetComments will run if we go from not being an admin -> being an admin, or will it also run if we go from being an admin -> not being an admin?

2021-04-28 15:21 UTC, kchadha commented on src/views/studio/studio-comments.jsx
> +};
Is this just for use in the test?

2021-04-28 15:34 UTC, kchadha commented on src/views/studio/studio-comments.jsx
> +    }, [isAdmin]);
Actually I think the test answers my question

2021-04-28 15:37 UTC, kchadha approved these changes
LGTM!

2021-04-28 15:38 UTC, kchadha requested changes
Oops just saw the merge conflicts. LGTM _after_ those are resolved.

2021-04-29 13:12 UTC, merged