Add comments not allowed box
LLK/scratch-www pull request #5500
Opened 2021-05-26 18:48 UTC by fsih

Add the comments not allowed box, and adjust the spacing around the comment compose box.

<img width="837" alt="Screen Shot 2021-05-26 at 14 46 27" src="https://user-images.githubusercontent.com/2855464/119714969-77f2ae00-be31-11eb-9bea-5711a548adcb.png">

2021-05-27 05:01 UTC, Naleksuh requested changes

2021-05-27 05:01 UTC, Naleksuh commented on src/views/studio/l10n.json
> +    "studio.commentsNotAllowed": "Commenting for this studio has been turned off.",
The message for profiles is:
> Sorry, comment posting has been turned off for this user profile. 
The message for projects is:
> Sorry, comment posting has been turned off for this project.
So the studio message here doesn't make sense. Should be something like "Sorry, comment posting has been turned off for this studio."

2021-06-01 19:38 UTC, seotts commented
This looks good to me! I tested locally, and it seems to work. Naleksuh makes a good point about the wording, but I don't think that needs to be fixed before deploy this week; might be worth checking in with Kathy about it after it's up on scratch.ly

2021-06-01 19:49 UTC, merged

2021-06-05 19:45 UTC, mxmou commented
This pull request increased the spacing around the compose row in project comments. Was this intentional?