Studio comments off
LLK/scratch-www pull request #5587
Opened 2021-06-10 20:53 UTC by picklesrus

Adds in comment status component to show when studio comments are off. 
![image](https://user-images.githubusercontent.com/15675877/121595465-4de1e400-ca0c-11eb-9ba4-66d2269362e4.png)

2021-06-10 20:53 UTC, picklesrus commented on src/views/studio/studio-comments.jsx
>              </div>
This part of the diff is much easier to read if you turn whitespace changes off.

2021-06-11 14:47 UTC, paulkaplan requested changes
A couple of questions/requests for changes. I'm happy to talk about the questions IRL.

2021-06-11 14:47 UTC, paulkaplan commented on src/redux/session.js
> +module.exports.selectStudioCommentsGloballyEnabled = state =>
@picklesrus I think that this should probably be true by default right until we hear from the session? I've been trying to make sure the path to trying to load stuff is as parallel as possible, and this change would prevent loading the comments list until the user session has been fetched, which isn't necessary.

2021-06-11 14:47 UTC, paulkaplan commented on src/views/studio/studio-comments.jsx
> +            {!hasFetchedSession || studioCommentsGloballyEnabled ?
Why is the `!hasFetchedSession` here blocking the comments from rendering? possibly related to my other comment about not blocking comment loading with session request

2021-06-14 21:29 UTC, picklesrus commented
This isn't finished (e.g.tests would need to be cleaned up), but I'm curious if you like this approach better

2021-06-15 19:21 UTC, paulkaplan commented
I approve of the direction. I like the unit test on studio-comments and probably would want a unit test on the permission selectors as well.

2021-06-15 22:34 UTC, picklesrus commented
Simplified the tests in studio-comments and moved them to studio-permissions. Glad they were there because they found a bug in the refactor. Fixed that and resolved some merge conflicts. Ready for another review!

2021-06-16 19:41 UTC, paulkaplan approved these changes
LGTM

2021-06-17 19:02 UTC, paulkaplan commented
Sorry about the continuing merge conflicts, there is a lot going on with studio comments right now. Should be settled now for at least a few days, but definitely recommend merging asap

2021-06-17 20:29 UTC, picklesrus commented
I added some test cases to handle the single comment mode. If they pass on Circle, I'm merging. :)

2021-06-17 20:34 UTC, merged