update maintenance and trouble page static content
LLK/scratch-www pull request #5594
Opened 2021-06-11 22:36 UTC by benjiwheeler

### Resolves:

Resolves https://github.com/LLK/scratch-www/issues/4914

### Changes:

* take "fixing a problem" content we previously had in maintenance.html, and copy it to trouble.html
* update language in each to be clearer about their distinct meaning, per https://docs.google.com/document/d/1D8gBGfrtEKTsiOpFiXbNzQNjZF4WHOld0nchtgZIHZA/edit
* update design with new images in S3 bucket, per Figma designs https://www.figma.com/file/L82ypZomFB9t6kcjRtesTV/Trouble-%2F-Maintenance-Page?node-id=203%3A45

Note that this PR will not make these pages actually be used! These files are just a convenient place to keep the static html/css/js content that we will paste into our Fastly services' synthetic responses.

## Screenshots

### Trouble page

![image](https://user-images.githubusercontent.com/3431616/121754895-c8316780-cae3-11eb-8c85-d3f101e073c9.png)

![image](https://user-images.githubusercontent.com/3431616/121754918-d1bacf80-cae3-11eb-93ad-0034776ffd69.png)

![image](https://user-images.githubusercontent.com/3431616/121754920-d4b5c000-cae3-11eb-85a0-7b2020708a9d.png)

### Maintenance page

![image](https://user-images.githubusercontent.com/3431616/121754929-daaba100-cae3-11eb-839e-0d4adbc35ab3.png)

![image](https://user-images.githubusercontent.com/3431616/121754932-dda69180-cae3-11eb-8100-68ac2fc5dbc0.png)

![image](https://user-images.githubusercontent.com/3431616/121754948-e5fecc80-cae3-11eb-891a-d5ffca0795ee.png)

2021-06-11 22:43 UTC, Accio1 commented
This is neat! I really like the little flowerpot and rock icons!

2021-06-14 01:25 UTC, Naleksuh requested changes
This URL is outdated and should be changed to https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe

2021-06-14 01:26 UTC, Naleksuh commented
> 
> 
> This URL is outdated and should be changed to https://downloads.scratch.mit.edu/desktop/Scratch%20Setup.exe

For some reason this didn't show what URL I was talking about. For clarity I meant the URL on line 203 of static/cdn/trouble.html

2021-06-14 16:10 UTC, benjiwheeler commented
blocked on getting design ok; then i'll need an engineer to review

2021-06-14 16:11 UTC, benjiwheeler commented
Design gave ok, thanks @kathymakes!

2021-06-15 18:28 UTC, benjiwheeler commented on static/cdn/maintenance.html
> +          <img src="http://scratch-maintenance.s3.amazonaws.com/cairn.svg" />
added this image to s3 bucket

2021-06-15 18:28 UTC, benjiwheeler commented on static/cdn/trouble.html
> +          <img src="http://scratch-maintenance.s3.amazonaws.com/wateringcan.svg" />
added this image to s3 bucket

2021-06-15 22:42 UTC, kchadha approved these changes
LGTM

2021-06-16 00:33 UTC, Naleksuh approved these changes
Link seems updated now

2021-06-16 18:54 UTC, merged

2021-06-17 02:40 UTC, benjiwheeler commented
FYI: I updated the maintenance and trouble page response content in both the scratch-www-staging and scratch-www-production fastly services.