Updated text on Code of Ethics page
LLK/scratch-www pull request #6471
Opened 2022-01-21 16:02 UTC by zoebentley

Changes: 
-Updated page text to match this document: https://docs.google.com/document/d/18o88J_C2MwjvUX77CzjM0TZGNfxRZfP2LvB-QLN9umw/edit

2022-01-21 16:55 UTC, apple502j commented on src/views/ethics/l10n.json
> +  "ethics.researchEmailLinkText": "research@scratchfoundation.org",
Email should not be translated.

2022-02-01 15:26 UTC, seotts requested changes
This looks good! Like apple502j shared, we don't translate emails. I made some suggests for how to include email instead.

2022-02-01 15:26 UTC, seotts commented on src/views/ethics/ethics.jsx
> +                            <FormattedMessage id="ethics.researchEmailLinkText" />
```suggestion
                            research@scratchfoundation.org
```

2022-02-01 15:26 UTC, seotts commented on src/views/ethics/l10n.json
> +  "ethics.researchEmailLinkText": "research@scratchfoundation.org",
```suggestion
```

2022-02-01 16:02 UTC, merged