Updates aqua and gray colors
LLK/scratch-www pull request #7306
Opened 2022-12-16 20:07 UTC by ChrisC

### Resolves:

Partially addresses #7182. Scratch product & design are currently thinking through further changes to the color palette to reach compliance.  

### Changes:

These changes affect the splash section on the `/splash` page and the tabs on the `/explore` to make them WCAG 2.1 AA compliant. Specifically, the aqua colors are darkened and darker text with outlines are used around grey button-like UI elements. See screenshots for previews of the changes:
<img width="1146" alt="image" src="https://user-images.githubusercontent.com/58723/208171107-d224f69e-fc1a-46d5-80ce-b03523f1b91d.png">

<img width="982" alt="image" src="https://user-images.githubusercontent.com/58723/208171147-473bec02-1655-4057-8176-fb36bc37a633.png">

### Test Coverage:

No tests changes and all automated tests currently pass.

2023-02-02 14:52 UTC, corihudson requested changes
@ChrisC Thanks for this PR! Converting these new colors to HSLA format for consistency would be good, but other than that these changes are great.

2023-02-02 14:52 UTC, corihudson commented on src/_colors.scss
> +$ui-aqua: #338554;
```suggestion
$ui-aqua: hsla(144, 45%, 36%, 1); 
```

2023-02-02 14:52 UTC, corihudson commented on src/_colors.scss
> +$type-dark-gray: #3B3B3B;
```suggestion
$type-dark-gray: hsla(0, 0%, 23%, 1);
```

2023-02-14 01:27 UTC, ChrisC commented
@corihudson Thanks for the feedback! Just made the requested changes 🙂

2023-02-14 15:46 UTC, corihudson approved these changes
Looks great to me, thanks for making those changes!

2023-02-14 15:46 UTC, merged