adds alt-text descriptions to the Ideas page
LLK/scratch-www pull request #7309
Opened 2022-12-16 23:12 UTC by ChrisC

### Resolves:

Partially addresses #7178 

### Changes:

Adds image descriptions to non-decorative images throughout the `/ideas` page. Also mutes decorative icons in various buttons throughout the Ideas page.

### Test Coverage:

No added tests but verified that this does not break existing tests.

2022-12-16 23:16 UTC, ChrisC commented
h/t to @alflennik for support on generating some of the more challenging alternative-text descriptions here!!

2023-03-22 20:14 UTC, corihudson requested changes
Spotted one tile where the image alt text wasn't pointing to the right l10n string, but otherwise looks great, thank you!

2023-03-22 20:14 UTC, corihudson commented on src/views/ideas/ttt.json
> +        "thumbImageDescription": "ideas.animateACharacterDescription",
```suggestion
        "thumbImageDescription": "ideas.animateACharacterImageDescription",
```

2023-03-22 20:14 UTC, corihudson commented on src/views/ideas/ttt.json
> +        "modalImageDescription": "ideas.animateACharacterDescription",
```suggestion
        "modalImageDescription": "ideas.animateACharacterImageDescription",
```

2023-04-05 22:33 UTC, ChrisC commented
@corihudson Thanks for spotting those translation key errors! Made the suggested changes 👍🏽

2023-04-06 18:54 UTC, corihudson approved these changes

2023-04-06 18:55 UTC, merged